kramdown:
  input: Kramdown

nav:
  - name: "Home"
    url: "/"
  - name: "Guidelines"
    url: "/guidelines/"
  - name: "Components"
    url: "/components/"
  - name: "Patterns"
    url: "/patterns/"
  - name: "Testing"
    url: "/testing/"

collections:
  icons:
    output: true
    permalink: /guidelines/iconography/:name

defaults:
  - scope:
      path: ""
      type: "icons"
    values:
      layout: "documentation-page-icon"