
kramdown:
  input: Kramdown

nav:
  - name: "Home"
    url: "/"
  - name: "Guidelines"
    url: "/guidelines/"
  - name: "Components"
    url: "/components/"
  - name: "Patterns"
    url: "/patterns/"