name: Sass build
on:
  workflow_dispatch:

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: _sass/site.scss
          destination: dist/css/site.css

      - name: Add and Commit changes back to main branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add dist/css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
