name: Sass to CSS Compiler

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  compile-sass:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Set up Node.js to run Sass
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Install Sass
    - name: Install Sass
      run: npm install -g sass

    # Compile Sass to CSS
    - name: Compile Sass files to CSS
      run: |
        sass _sass/site.scss:dist/css/site.css --no-source-map

    # Commit and push the CSS changes
    - name: Push changes
      run: |
        git checkout -b update-css
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Energy-Saving-Trust/Design-System.git update-css
        
  create-pr:
    needs: compile-sass
    runs-on: ubuntu-latest
    if: success()

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Create Pull Request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Update compiled CSS"
        branch: update-css
        title: "Update compiled CSS"
        body: "This PR updates the compiled CSS from the latest Sass changes."
        base: main
